version: "3.9"

services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: pgpooladmin-api
    restart: always
    # ports:
    #   - "8000:8000"
    networks:
      - application-network
    env_file:
      - ./api/.env.local
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  console:
    build:
      context: console
      dockerfile: Dockerfile
    container_name: pgpooladmin-console
    restart: always
    # ports:
    #   - "3000:3000"
    networks:
      - application-network
    depends_on:
      - api
    env_file:
      - ./console/.env.local
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  application-network:
    external: true
